version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:lts
      - working_directory: ~/repo
    steps:
      - checkout
      - run: echo "test"
      - run: npm install
      - run: npm test
