version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Build and test
          command: |
            cd snykTask
            pwd
            ls -la
            npm install
            npm run eslint
            npm run format:check
            npm test

  deploy-test:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - azure-cli/install
      - run: which az
      - run:
          name: Test
          command: |
            cd snykTask
            node -v
            az devops --help
            export AZURE_DEVOPS_EXT_PAT=$AZ_TEST_TOKEN
            az devops login --organization $AZ_TEST_ORG
            az devops extension list --organization $AZ_TEST_ORG --output table

orbs:
  azure-cli: circleci/azure-cli@1.0.0

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy-test:
          requires:
            - build
          filters:
            branches:
              only: feat/initial-implementation

