version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Build and test
          command: |
            cd snykTask
            pwd
            ls -la
            npm install
            npm run eslint
            npm run format:check
            npm test

  deploy-test:
    docker:
      - image: circleci/node:lts
    steps:
#      - checkout
      - run:
          name: Test
          command: echo "pretend to deploy"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy-test:
          requires:
            - build
          filters:
            branches:
              only: feat/initial-implementation
              ignore:
                - master
                - develop
