version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Build and test
          command: |
            cd snykTask
            pwd
            ls -la
            npm install
            npm run eslint
            npm run format:check
            npm test

  deploy-test:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - azure-cli/install
      - run: which az
      - run: az extension add --name azure-devops
      - run:
          name: Publish to test Azure
          command: |
            cd snykTask
            npm install
            tsc
            npm prune --production
            cd ..
            export AZURE_DEVOPS_EXT_PAT=$AZ_TEST_TOKEN
            az devops --help
            sudo npm install -g tfx-cli
            which tfx
            az devops extension uninstall --publisher-name $AZ_TEST_PUB_NAME --extension-name $AZ_EXTENSION_NAME --organization $AZ_TEST_ORG --yes
            tfx extension publish --manifest-globs vss-extension.json --rev-version --share-with $AZ_TEST_SHARE_WITH_ORG --token $AZURE_DEVOPS_EXT_PAT
            az devops extension install --publisher-name $AZ_TEST_PUB_NAME --extension-name $AZ_EXTENSION_NAME --organization $AZ_TEST_ORG
            az devops extension list --organization $AZ_TEST_ORG --output table

orbs:
  azure-cli: circleci/azure-cli@1.0.0

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy-test:
          requires:
            - build
          filters:
            branches:
              only: feat/initial-implementation

