version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:lts

    working_directory: ~/repo

    steps:
      - checkout
      - run: echo "test"
      - run: pwd
      - run:
          name: Build and test
          command: |
            cd snykTask
            pwd
            ls -la
            npm install
            npm test
