version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Build and test
          command: |
            cd snykTask
            pwd
            ls -la
            npm install
            npm run build
            npm run eslint
            npm run format:check
            npm test


orbs:
  azure-cli: circleci/azure-cli@1.0.0

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
