version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Build
          command: |
            ./scripts/ci-build.sh
      - run:
          name: Checks
          command: |
            npm run test:checks
      - run:
          name: Unit Tests
          command: |
            npm run test:unit
      - run:
          name: System Tests
          command: |
            npm run test:system

  deploy:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Build and Deploy
          command: |
            npm install
            npx semantic-release

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - deploy:
          context: nodejs-lib-release
          requires:
            - test
          filters:
            branches:
              only: master
